### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by JuchangGit** [v-mars/jobor#1]
[GIN] 2021/05/31 - 17:56:58 | 200 |     1.06781ms |       127.0.0.1 | POST     "/api/login"
[ERROR] 2021-05-31 17:56:58 - 用户: nil, 方法: POST, URL: /api/login, CODE: 200, 耗时: 1ms, Body数据: {"username":"admin","password":"admin"}, 
ERROR: Error 1054: Unknown column 'user_type_id' in 'where clause'

**Comment by laixiaohuai** [comment]
fixed
请重新拉包
