### ISSUE TITLE
二进制部署，访问网页报错，unexpected fault address 0x0

### ISSUE THREAD

**Issue by Makzhou** [v-mars/jobor#11]
访问网页报错，http://192.168.0.236:5000/#/
----------------------------------------------------------
[GIN] 2023/08/13 - 14:44:40 | 200 |   131.37023ms |    192.168.0.11 | GET      "/static/js/chunk-elementUI.8e263ae8.js"
[GIN] 2023/08/13 - 14:44:40 | 200 |  169.491892ms |    192.168.0.11 | GET      "/static/js/chunk-libs.a1ab8e61.js"
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4664df]

goroutine 32 [running]:
runtime.throw({0x123b7db?, 0x7f290fc3d2c0?})
        /opt/tool/go/src/runtime/panic.go:992 +0x71 fp=0xc000fd6ab8 sp=0xc000fd6a88 pc=0x435f71
runtime.sigpanic()
        /opt/tool/go/src/runtime/signal_unix.go:825 +0x305 fp=0xc000fd6b08 sp=0xc000fd6ab8 pc=0x44c1c5
aeshashbody()
        /opt/tool/go/src/runtime/asm_amd64.s:1343 +0x39f fp=0xc000fd6b10 sp=0xc000fd6b08 pc=0x4664df
runtime.mapiternext(0xc000127100)
        /opt/tool/go/src/runtime/map.go:934 +0x2cb fp=0xc000fd6b80 sp=0xc000fd6b10 pc=0x40fd2b
runtime.mapiterinit(0xc0001dc750?, 0x0?, 0xc00256c150?)
        /opt/tool/go/src/runtime/map.go:861 +0x228 fp=0xc000fd6ba0 sp=0xc000fd6b80 pc=0x40fa08
reflect.mapiterinit(0x10a2f40?, 0xc0001dc758?, 0xc000fd6cb0?)
        /opt/tool/go/src/runtime/map.go:1373 +0x19 fp=0xc000fd6bc8 sp=0xc000fd6ba0 pc=0x462919
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /opt/tool/golang/pkg/mod/github.com/modern-go/reflect2@v1.0.1/unsafe_map.go:112
github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc00256c2d0, 0xc0001882e8, 0xc00007f7a0)
        /opt/tool/golang/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect_map.go:291 +0x225 fp=0xc000fd6d30 sp=0xc000fd6bc8 pc=0xbf5da5
github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc0002f5f20, 0xc000a1df80, 0xc000127100?)
        /opt/tool/golang/pkg/mod/github.com/json-iterator/go@v1.1.9/reflect.go:219 +0x82 fp=0xc000fd6d68 sp=0xc000fd6d30 pc=0xbee522

**Comment by laixiaohuai** [comment]
项目已经重构，已知问题都修复，并且加很多新功能
