### ISSUE TITLE
AddTask Event

### ISSUE THREAD

**Issue by liangjfblue** [v-mars/jobor#19]
https://github.com/v-mars/jobor/blob/504de766505ce845b848f9be36477d5d5884129d/biz/model/task.go#L247

`ChangeEvent` should be changed to `AddEvent` ?

**Comment by laixiaohuai** [comment]
一样的效果，用changeEvent兼容性更强，在已经存在任务的情况下，保障还不会产生错

**Comment by liangjfblue** [comment]
@laixiaohuai okey
