### ISSUE TITLE
无法添加admin用户

### ISSUE THREAD

**Issue by JuchangGit** [v-mars/jobor#3]
![image](https://user-images.githubusercontent.com/34911052/120737200-38f2e580-c520-11eb-84e1-f0b782536cbe.png)
![image](https://user-images.githubusercontent.com/34911052/120737298-6c357480-c520-11eb-83f8-57bea7583a09.png)
永远不会执行StartInstall()函数

**Comment by JuchangGit** [comment]
因为
func initDB(config *config.Config){
	models.InitDB(config)
	models.Migration()
}
这块总是会执行，导致 install变量值始终是 true

**Comment by laixiaohuai** [comment]
你加我微信聊吧，我最近比较忙
boen1990


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "v-mars/jobor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 上午10:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[v-mars/jobor] 无法添加admin用户 (#3)





 

 
 永远不会执行StartInstall()函数
