### ISSUE TITLE
今天发现线上无法修改添加任务，返回需要认证

### ISSUE THREAD

**Issue by huxxhua** [v-mars/jobor#8]
**无法修改添加任务**
`{
    "code": 400,
    "message": "channel [jobor.event] publish the message err: NOAUTH Authentication required.\n",
    "status": "error",
    "data": null
}`
![O channel flobor eventl publish the message e NOAUTH Authentication required](https://user-images.githubusercontent.com/20944512/163983689-b0b23679-7783-41df-b508-cb3e22975057.png)
<img width="856" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/20944512/163983709-7add85d1-6d9c-4967-8ff7-c917ccffd97c.png">

**Comment by laixiaohuai** [comment]
> **无法修改添加任务** `{ "code": 400, "message": "channel [jobor.event] publish the message err: NOAUTH Authentication required.\n", "status": "error", "data": null }` ![O channel flobor eventl publish the message e NOAUTH Authentication required](https://user-images.githubusercontent.com/20944512/163983689-b0b23679-7783-41df-b508-cb3e22975057.png) <img alt="Pasted Graphic" width="856" src="https://user-images.githubusercontent.com/20944512/163983709-7add85d1-6d9c-4967-8ff7-c917ccffd97c.png">

redis开启了认证？
